name: Main branch tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Test with coverage
      run: |
        dotnet test \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --settings coverlet.runsettings \
          --logger trx

    - name: Generate Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.25
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'Badges;HtmlInline_AzurePipelines;Cobertura'

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coveragereport

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./**/coverage.info

    - name: Publish
      run: dotnet publish -c Release -o ./Publish --no-build

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-data
        path: ./Publish/**