name: Main branch tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Publish
      run: dotnet publish -c Release -o ./Publish --no-build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Release build
        path: ./Publish
        if-no-files-found: error

    - name: Get coverage report
      run: | 
        dotnet test ProfileProjectTests/ProfileProjectTests.csproj 
        /p:CollectCoverage=true 
        /p:CoverletOutputFormat=cobertura 
        /p:CoverletOutput=./TestResults/ 
        /p:ExcludeByFile=\"**/Models/**/*.cs%2c**/Data/Migrations/**/*.cs%2c**/Data/Attributes/**/*.cs%2c**/*.cshtml%2c**/*.cshtml%2c**/*.cshtml%2c**/*.cshtml\"

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
        file: ./ProfileProjectTests/TestResults/coverage.cobertura.xml