name: Main branch tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./Publish --no-build

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-data
        path: ./Publish/

    - name: Run tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: ./**/lcov.info 
        repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }} 