name: Main branch tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Publish
      run: dotnet publish -c Release -o ./Publish --no-build

    - name: Get coverage report
      run: | 
        dotnet test --collect:"XPlat Code Coverage;Format=cobertura"
        find . -type f -name "coverage.opencover.xml"

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
        file: 